FROM docker.io/rancher/mirrored-coredns-coredns:1.10.1
COPY ./Corefile /tmp/Corefile
WORKDIR /app
COPY ./bin/kl-coredns /app/kl-coredns
EXPOSE 53 53/udp
ENTRYPOINT ["/app/kl-coredns", "--addr", ":22222", "--corefile", "/tmp/Corefile"]
