// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Check struct {
	Status     *bool   `json:"Status"`
	Message    *string `json:"Message"`
	Generation *int    `json:"Generation"`
}

type CloudProviderSpecIn struct {
	AccountName    string                             `json:"accountName"`
	ProviderSecret *CloudProviderSpecProviderSecretIn `json:"providerSecret"`
}

type CloudProviderSpecProviderSecret struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type CloudProviderSpecProviderSecretIn struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type ClusterSpecIn struct {
	AccountName  string `json:"accountName"`
	Config       string `json:"config"`
	Count        int    `json:"count"`
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
}

type EdgeSpecIn struct {
	Provider     *string          `json:"provider"`
	ProviderName string           `json:"providerName"`
	Region       string           `json:"region"`
	AccountName  string           `json:"accountName"`
	ClusterName  string           `json:"clusterName"`
	Pools        *EdgeSpecPoolsIn `json:"pools"`
}

type EdgeSpecPools struct {
	Min    *int   `json:"min"`
	Name   string `json:"name"`
	Config string `json:"config"`
	Max    *int   `json:"max"`
}

type EdgeSpecPoolsIn struct {
	Min    *int   `json:"min"`
	Name   string `json:"name"`
	Config string `json:"config"`
	Max    *int   `json:"max"`
}

type MasterNodeSpec struct {
	Config       string `json:"config"`
	MysqlURI     string `json:"mysqlURI"`
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	AccountName  string `json:"accountName"`
	ClusterName  string `json:"clusterName"`
}

type MasterNodeSpecIn struct {
	Config       string `json:"config"`
	MysqlURI     string `json:"mysqlURI"`
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	AccountName  string `json:"accountName"`
	ClusterName  string `json:"clusterName"`
}

type NodePoolSpec struct {
	Config       string `json:"config"`
	Max          *int   `json:"max"`
	ClusterName  string `json:"clusterName"`
	EdgeName     string `json:"edgeName"`
	Min          *int   `json:"min"`
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	AccountName  string `json:"accountName"`
}

type NodePoolSpecIn struct {
	Config       string `json:"config"`
	Max          *int   `json:"max"`
	ClusterName  string `json:"clusterName"`
	EdgeName     string `json:"edgeName"`
	Min          *int   `json:"min"`
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	AccountName  string `json:"accountName"`
}

type WorkerNodeSpec struct {
	NodeIndex    *int   `json:"nodeIndex"`
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	Pool         string `json:"pool"`
	Stateful     *bool  `json:"stateful"`
	AccountName  string `json:"accountName"`
	ClusterName  string `json:"clusterName"`
	Config       string `json:"config"`
	EdgeName     string `json:"edgeName"`
}

type WorkerNodeSpecIn struct {
	NodeIndex    *int   `json:"nodeIndex"`
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	Pool         string `json:"pool"`
	Stateful     *bool  `json:"stateful"`
	AccountName  string `json:"accountName"`
	ClusterName  string `json:"clusterName"`
	Config       string `json:"config"`
	EdgeName     string `json:"edgeName"`
}
