package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"fmt"
	"time"

	"github.com/kloudlite/api/apps/container-registry/internal/app/graph/generated"
	"github.com/kloudlite/api/apps/container-registry/internal/domain/entities"
)

// CreationTime is the resolver for the creationTime field.
func (r *digestResolver) CreationTime(ctx context.Context, obj *entities.Digest) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("build is nil")
	}

	return obj.CreationTime.Format(time.RFC3339), nil
}

// ID is the resolver for the id field.
func (r *digestResolver) ID(ctx context.Context, obj *entities.Digest) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("build is nil")
	}

	return string(obj.Id), nil
}

// UpdateTime is the resolver for the updateTime field.
func (r *digestResolver) UpdateTime(ctx context.Context, obj *entities.Digest) (string, error) {
	if obj == nil {
		return "", fmt.Errorf("build is nil")
	}

	return obj.UpdateTime.Format(time.RFC3339), nil
}

// Digest returns generated.DigestResolver implementation.
func (r *Resolver) Digest() generated.DigestResolver { return &digestResolver{r} }

type digestResolver struct{ *Resolver }
