# FROM gcr.io/distroless/static-debian12:nonroot
FROM alpine:3.16

RUN apk add bash
COPY --from=docker.io/vectorized/redpanda:v22.1.6 /usr/bin/rpk /usr/local/bin/rpk
COPY --from=docker.io/vectorized/redpanda:v22.1.6 /opt/redpanda/libexec/rpk /opt/redpanda/libexec/rpk

WORKDIR /app

ARG binpath
COPY --from=local-builder ${binpath} ./messages-distribution-worker
USER 65535:65535
ENTRYPOINT [ "./messages-distribution-worker" ]
