// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"kloudlite.io/pkg/repos"
)

type GitPipeline struct {
	ID                   repos.ID               `json:"id"`
	RepoName             string                 `json:"repoName"`
	Name                 string                 `json:"name"`
	ImageName            string                 `json:"imageName"`
	GitProvider          string                 `json:"gitProvider"`
	GitRepoURL           string                 `json:"gitRepoUrl"`
	GitBranch            string                 `json:"gitBranch"`
	DockerFile           *string                `json:"dockerFile"`
	ContextDir           *string                `json:"contextDir"`
	GithubInstallationID *int                   `json:"githubInstallationId"`
	GitlabRepoID         *int                   `json:"gitlabRepoId"`
	BuildArgs            map[string]interface{} `json:"buildArgs"`
	Metadata             map[string]interface{} `json:"metadata"`
}

type GitPipelineIn struct {
	Name                 string                 `json:"name"`
	ImageName            string                 `json:"imageName"`
	GitProvider          string                 `json:"gitProvider"`
	GitRepoURL           string                 `json:"gitRepoUrl"`
	RepoName             string                 `json:"repoName"`
	GitBranch            string                 `json:"gitBranch"`
	DockerFile           *string                `json:"dockerFile"`
	ContextDir           *string                `json:"contextDir"`
	GithubInstallationID *int                   `json:"githubInstallationId"`
	GitlabRepoID         *int                   `json:"gitlabRepoId"`
	BuildArgs            map[string]interface{} `json:"buildArgs"`
}

type Kv struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type PipelineDataInput struct {
	Name                 string                 `json:"name"`
	ImageName            string                 `json:"imageName"`
	RepoName             string                 `json:"repoName"`
	GitProvider          string                 `json:"gitProvider"`
	GitRepoURL           string                 `json:"gitRepoUrl"`
	GitlabRepoID         int                    `json:"gitlabRepoId"`
	DockerFile           string                 `json:"dockerFile"`
	ContextDir           string                 `json:"contextDir"`
	GithubInstallationID *int                   `json:"githubInstallationId"`
	BuildArgs            map[string]interface{} `json:"buildArgs"`
	Branch               string                 `json:"branch"`
	Metadata             map[string]interface{} `json:"metadata"`
}
