apiVersion: platform.kloudlite.io/v1alpha1
kind: User
metadata:
  name: super-admin
spec:
  email: super-admin@kloudlite.io
  displayName: Super Admin
  password: karthik001
  active: true
  roles:
    - super-admin
