// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BYOCClusterSpec struct {
	Provider           string    `json:"provider"`
	PublicIps          []*string `json:"publicIps,omitempty"`
	Region             string    `json:"region"`
	StorageClasses     []*string `json:"storageClasses,omitempty"`
	AccountName        string    `json:"accountName"`
	DisplayName        *string   `json:"displayName,omitempty"`
	IncomingKafkaTopic string    `json:"incomingKafkaTopic"`
	IngressClasses     []*string `json:"ingressClasses,omitempty"`
}

type BYOCClusterSpecIn struct {
	Provider           string    `json:"provider"`
	PublicIps          []*string `json:"publicIps,omitempty"`
	Region             string    `json:"region"`
	StorageClasses     []*string `json:"storageClasses,omitempty"`
	AccountName        string    `json:"accountName"`
	DisplayName        *string   `json:"displayName,omitempty"`
	IncomingKafkaTopic string    `json:"incomingKafkaTopic"`
	IngressClasses     []*string `json:"ingressClasses,omitempty"`
}

type CloudProviderSpec struct {
	DisplayName    string                           `json:"display_name"`
	Provider       string                           `json:"provider"`
	ProviderSecret *CloudProviderSpecProviderSecret `json:"providerSecret"`
	AccountName    string                           `json:"accountName"`
}

type CloudProviderSpecIn struct {
	DisplayName    string                             `json:"display_name"`
	Provider       string                             `json:"provider"`
	ProviderSecret *CloudProviderSpecProviderSecretIn `json:"providerSecret"`
	AccountName    string                             `json:"accountName"`
}

type CloudProviderSpecProviderSecret struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type CloudProviderSpecProviderSecretIn struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type ClusterSpec struct {
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	AccountName  string `json:"accountName"`
	Config       string `json:"config"`
	Count        int    `json:"count"`
}

type ClusterSpecIn struct {
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	AccountName  string `json:"accountName"`
	Config       string `json:"config"`
	Count        int    `json:"count"`
}

type EdgeSpec struct {
	AccountName  string           `json:"accountName"`
	ClusterName  string           `json:"clusterName"`
	Pools        []*EdgeSpecPools `json:"pools,omitempty"`
	Provider     *string          `json:"provider,omitempty"`
	ProviderName string           `json:"providerName"`
	Region       string           `json:"region"`
}

type EdgeSpecIn struct {
	AccountName  string             `json:"accountName"`
	ClusterName  string             `json:"clusterName"`
	Pools        []*EdgeSpecPoolsIn `json:"pools,omitempty"`
	Provider     *string            `json:"provider,omitempty"`
	ProviderName string             `json:"providerName"`
	Region       string             `json:"region"`
}

type EdgeSpecPools struct {
	Name   string `json:"name"`
	Config string `json:"config"`
	Max    *int   `json:"max,omitempty"`
	Min    *int   `json:"min,omitempty"`
}

type EdgeSpecPoolsIn struct {
	Name   string `json:"name"`
	Config string `json:"config"`
	Max    *int   `json:"max,omitempty"`
	Min    *int   `json:"min,omitempty"`
}

type MasterNodeSpec struct {
	Region       string `json:"region"`
	AccountName  string `json:"accountName"`
	ClusterName  string `json:"clusterName"`
	Config       string `json:"config"`
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
}

type MasterNodeSpecIn struct {
	Region       string `json:"region"`
	AccountName  string `json:"accountName"`
	ClusterName  string `json:"clusterName"`
	Config       string `json:"config"`
	Provider     string `json:"provider"`
	ProviderName string `json:"providerName"`
}

type NodePoolSpec struct {
	AccountName  string `json:"accountName"`
	Config       string `json:"config"`
	Max          *int   `json:"max,omitempty"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	ClusterName  string `json:"clusterName"`
	EdgeName     string `json:"edgeName"`
	Min          *int   `json:"min,omitempty"`
	Provider     string `json:"provider"`
}

type NodePoolSpecIn struct {
	AccountName  string `json:"accountName"`
	Config       string `json:"config"`
	Max          *int   `json:"max,omitempty"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	ClusterName  string `json:"clusterName"`
	EdgeName     string `json:"edgeName"`
	Min          *int   `json:"min,omitempty"`
	Provider     string `json:"provider"`
}

type WorkerNodeSpec struct {
	ClusterName  string `json:"clusterName"`
	Config       string `json:"config"`
	NodeIndex    *int   `json:"nodeIndex,omitempty"`
	Pool         string `json:"pool"`
	Provider     string `json:"provider"`
	AccountName  string `json:"accountName"`
	EdgeName     string `json:"edgeName"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	Stateful     *bool  `json:"stateful,omitempty"`
}

type WorkerNodeSpecIn struct {
	ClusterName  string `json:"clusterName"`
	Config       string `json:"config"`
	NodeIndex    *int   `json:"nodeIndex,omitempty"`
	Pool         string `json:"pool"`
	Provider     string `json:"provider"`
	AccountName  string `json:"accountName"`
	EdgeName     string `json:"edgeName"`
	ProviderName string `json:"providerName"`
	Region       string `json:"region"`
	Stateful     *bool  `json:"stateful,omitempty"`
}
