#infra
infra.run: export SSH_KEYS_PATH=${HOME}/tmp/kloudlite/keys
infra.run: export KAFKA_INFRA_ACTION_RESULT_TOPIC=kloudlite-infra-action-result
infra.run: export DO_API_KEY=***REMOVED***
infra.run: export DATA_PATH=${HOME}/tmp/kloudlite/data
infra.run: export DO_IMAGE_ID=105912706
infra.run:
	go run main.go
