// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.3
// source: accounts-internal.proto

package accounts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AccountName string `protobuf:"bytes,2,opt,name=accountName,proto3" json:"accountName,omitempty"`
}

func (x *GetAccountIn) Reset() {
	*x = GetAccountIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounts_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountIn) ProtoMessage() {}

func (x *GetAccountIn) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountIn.ProtoReflect.Descriptor instead.
func (*GetAccountIn) Descriptor() ([]byte, []int) {
	return file_accounts_internal_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountIn) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAccountIn) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type GetAccountOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsActive               bool   `protobuf:"varint,1,opt,name=isActive,proto3" json:"isActive,omitempty"`
	TargetNamespace        string `protobuf:"bytes,2,opt,name=targetNamespace,proto3" json:"targetNamespace,omitempty"`
	AccountId              string `protobuf:"bytes,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	KloudliteGatewayRegion string `protobuf:"bytes,4,opt,name=kloudliteGatewayRegion,proto3" json:"kloudliteGatewayRegion,omitempty"`
}

func (x *GetAccountOut) Reset() {
	*x = GetAccountOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounts_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountOut) ProtoMessage() {}

func (x *GetAccountOut) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountOut.ProtoReflect.Descriptor instead.
func (*GetAccountOut) Descriptor() ([]byte, []int) {
	return file_accounts_internal_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountOut) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetAccountOut) GetTargetNamespace() string {
	if x != nil {
		return x.TargetNamespace
	}
	return ""
}

func (x *GetAccountOut) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountOut) GetKloudliteGatewayRegion() string {
	if x != nil {
		return x.KloudliteGatewayRegion
	}
	return ""
}

type GetPlatformSettingsInternalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPlatformSettingsInternalRequest) Reset() {
	*x = GetPlatformSettingsInternalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounts_internal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlatformSettingsInternalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformSettingsInternalRequest) ProtoMessage() {}

func (x *GetPlatformSettingsInternalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_internal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformSettingsInternalRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformSettingsInternalRequest) Descriptor() ([]byte, []int) {
	return file_accounts_internal_proto_rawDescGZIP(), []int{2}
}

type GetPlatformSettingsInternalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settings *PlatformSettingsInternal `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
}

func (x *GetPlatformSettingsInternalResponse) Reset() {
	*x = GetPlatformSettingsInternalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounts_internal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlatformSettingsInternalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformSettingsInternalResponse) ProtoMessage() {}

func (x *GetPlatformSettingsInternalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_internal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformSettingsInternalResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformSettingsInternalResponse) Descriptor() ([]byte, []int) {
	return file_accounts_internal_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlatformSettingsInternalResponse) GetSettings() *PlatformSettingsInternal {
	if x != nil {
		return x.Settings
	}
	return nil
}

type PlatformSettingsInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlatformOwnerEmail string                         `protobuf:"bytes,1,opt,name=platformOwnerEmail,proto3" json:"platformOwnerEmail,omitempty"`
	SupportEmail       string                         `protobuf:"bytes,2,opt,name=supportEmail,proto3" json:"supportEmail,omitempty"`
	AllowSignup        bool                           `protobuf:"varint,3,opt,name=allowSignup,proto3" json:"allowSignup,omitempty"`
	OauthProviders     *OAuthProviderSettingsInternal `protobuf:"bytes,4,opt,name=oauthProviders,proto3" json:"oauthProviders,omitempty"`
	TeamSettings       *TeamSettingsInternal          `protobuf:"bytes,5,opt,name=teamSettings,proto3" json:"teamSettings,omitempty"`
	Features           *PlatformFeaturesInternal      `protobuf:"bytes,6,opt,name=features,proto3" json:"features,omitempty"`
}

func (x *PlatformSettingsInternal) Reset() {
	*x = PlatformSettingsInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounts_internal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatformSettingsInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformSettingsInternal) ProtoMessage() {}

func (x *PlatformSettingsInternal) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_internal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformSettingsInternal.ProtoReflect.Descriptor instead.
func (*PlatformSettingsInternal) Descriptor() ([]byte, []int) {
	return file_accounts_internal_proto_rawDescGZIP(), []int{4}
}

func (x *PlatformSettingsInternal) GetPlatformOwnerEmail() string {
	if x != nil {
		return x.PlatformOwnerEmail
	}
	return ""
}

func (x *PlatformSettingsInternal) GetSupportEmail() string {
	if x != nil {
		return x.SupportEmail
	}
	return ""
}

func (x *PlatformSettingsInternal) GetAllowSignup() bool {
	if x != nil {
		return x.AllowSignup
	}
	return false
}

func (x *PlatformSettingsInternal) GetOauthProviders() *OAuthProviderSettingsInternal {
	if x != nil {
		return x.OauthProviders
	}
	return nil
}

func (x *PlatformSettingsInternal) GetTeamSettings() *TeamSettingsInternal {
	if x != nil {
		return x.TeamSettings
	}
	return nil
}

func (x *PlatformSettingsInternal) GetFeatures() *PlatformFeaturesInternal {
	if x != nil {
		return x.Features
	}
	return nil
}

type OAuthProviderSettingsInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Google    *OAuthProviderInternal          `protobuf:"bytes,1,opt,name=google,proto3" json:"google,omitempty"`
	Github    *OAuthProviderInternal          `protobuf:"bytes,2,opt,name=github,proto3" json:"github,omitempty"`
	Microsoft *MicrosoftOAuthProviderInternal `protobuf:"bytes,3,opt,name=microsoft,proto3" json:"microsoft,omitempty"`
}

func (x *OAuthProviderSettingsInternal) Reset() {
	*x = OAuthProviderSettingsInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounts_internal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OAuthProviderSettingsInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthProviderSettingsInternal) ProtoMessage() {}

func (x *OAuthProviderSettingsInternal) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_internal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthProviderSettingsInternal.ProtoReflect.Descriptor instead.
func (*OAuthProviderSettingsInternal) Descriptor() ([]byte, []int) {
	return file_accounts_internal_proto_rawDescGZIP(), []int{5}
}

func (x *OAuthProviderSettingsInternal) GetGoogle() *OAuthProviderInternal {
	if x != nil {
		return x.Google
	}
	return nil
}

func (x *OAuthProviderSettingsInternal) GetGithub() *OAuthProviderInternal {
	if x != nil {
		return x.Github
	}
	return nil
}

func (x *OAuthProviderSettingsInternal) GetMicrosoft() *MicrosoftOAuthProviderInternal {
	if x != nil {
		return x.Microsoft
	}
	return nil
}

type OAuthProviderInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled      bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ClientId     string `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientSecret string `protobuf:"bytes,3,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
}

func (x *OAuthProviderInternal) Reset() {
	*x = OAuthProviderInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounts_internal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OAuthProviderInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthProviderInternal) ProtoMessage() {}

func (x *OAuthProviderInternal) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_internal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthProviderInternal.ProtoReflect.Descriptor instead.
func (*OAuthProviderInternal) Descriptor() ([]byte, []int) {
	return file_accounts_internal_proto_rawDescGZIP(), []int{6}
}

func (x *OAuthProviderInternal) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *OAuthProviderInternal) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthProviderInternal) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type MicrosoftOAuthProviderInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled      bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ClientId     string `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientSecret string `protobuf:"bytes,3,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	TenantId     string `protobuf:"bytes,4,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
}

func (x *MicrosoftOAuthProviderInternal) Reset() {
	*x = MicrosoftOAuthProviderInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounts_internal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MicrosoftOAuthProviderInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicrosoftOAuthProviderInternal) ProtoMessage() {}

func (x *MicrosoftOAuthProviderInternal) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_internal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicrosoftOAuthProviderInternal.ProtoReflect.Descriptor instead.
func (*MicrosoftOAuthProviderInternal) Descriptor() ([]byte, []int) {
	return file_accounts_internal_proto_rawDescGZIP(), []int{7}
}

func (x *MicrosoftOAuthProviderInternal) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MicrosoftOAuthProviderInternal) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MicrosoftOAuthProviderInternal) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *MicrosoftOAuthProviderInternal) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type TeamSettingsInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequireApproval      bool  `protobuf:"varint,1,opt,name=requireApproval,proto3" json:"requireApproval,omitempty"`
	AutoApproveFirstTeam bool  `protobuf:"varint,2,opt,name=autoApproveFirstTeam,proto3" json:"autoApproveFirstTeam,omitempty"`
	MaxTeamsPerUser      int32 `protobuf:"varint,3,opt,name=maxTeamsPerUser,proto3" json:"maxTeamsPerUser,omitempty"`
}

func (x *TeamSettingsInternal) Reset() {
	*x = TeamSettingsInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounts_internal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeamSettingsInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamSettingsInternal) ProtoMessage() {}

func (x *TeamSettingsInternal) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_internal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamSettingsInternal.ProtoReflect.Descriptor instead.
func (*TeamSettingsInternal) Descriptor() ([]byte, []int) {
	return file_accounts_internal_proto_rawDescGZIP(), []int{8}
}

func (x *TeamSettingsInternal) GetRequireApproval() bool {
	if x != nil {
		return x.RequireApproval
	}
	return false
}

func (x *TeamSettingsInternal) GetAutoApproveFirstTeam() bool {
	if x != nil {
		return x.AutoApproveFirstTeam
	}
	return false
}

func (x *TeamSettingsInternal) GetMaxTeamsPerUser() int32 {
	if x != nil {
		return x.MaxTeamsPerUser
	}
	return 0
}

type PlatformFeaturesInternal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnableDeviceFlow bool `protobuf:"varint,1,opt,name=enableDeviceFlow,proto3" json:"enableDeviceFlow,omitempty"`
	EnableCLI        bool `protobuf:"varint,2,opt,name=enableCLI,proto3" json:"enableCLI,omitempty"`
	EnableAPI        bool `protobuf:"varint,3,opt,name=enableAPI,proto3" json:"enableAPI,omitempty"`
}

func (x *PlatformFeaturesInternal) Reset() {
	*x = PlatformFeaturesInternal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accounts_internal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatformFeaturesInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformFeaturesInternal) ProtoMessage() {}

func (x *PlatformFeaturesInternal) ProtoReflect() protoreflect.Message {
	mi := &file_accounts_internal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformFeaturesInternal.ProtoReflect.Descriptor instead.
func (*PlatformFeaturesInternal) Descriptor() ([]byte, []int) {
	return file_accounts_internal_proto_rawDescGZIP(), []int{9}
}

func (x *PlatformFeaturesInternal) GetEnableDeviceFlow() bool {
	if x != nil {
		return x.EnableDeviceFlow
	}
	return false
}

func (x *PlatformFeaturesInternal) GetEnableCLI() bool {
	if x != nil {
		return x.EnableCLI
	}
	return false
}

func (x *PlatformFeaturesInternal) GetEnableAPI() bool {
	if x != nil {
		return x.EnableAPI
	}
	return false
}

var File_accounts_internal_proto protoreflect.FileDescriptor

var file_accounts_internal_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0xab, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x12, 0x28, 0x0a, 0x0f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x16, 0x6b, 0x6c, 0x6f,
	0x75, 0x64, 0x6c, 0x69, 0x74, 0x65, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x6b, 0x6c, 0x6f, 0x75, 0x64,
	0x6c, 0x69, 0x74, 0x65, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x22, 0x24, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35,
	0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x08, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0xca, 0x02, 0x0a, 0x18, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x12, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x53,
	0x69, 0x67, 0x6e, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x46, 0x0a, 0x0e, 0x6f, 0x61, 0x75, 0x74,
	0x68, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x52, 0x0e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x73,
	0x12, 0x39, 0x0a, 0x0c, 0x74, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x0c, 0x74,
	0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x22, 0xbe, 0x01, 0x0a, 0x1d, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x06, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x06, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x06, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x12, 0x3d, 0x0a, 0x09, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f, 0x66,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x6f, 0x66, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x09, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x6f, 0x66, 0x74, 0x22, 0x71, 0x0a, 0x15, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x1e, 0x4d, 0x69, 0x63, 0x72, 0x6f,
	0x73, 0x6f, 0x66, 0x74, 0x4f, 0x41, 0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x9e, 0x01, 0x0a, 0x14, 0x54, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x61, 0x6c, 0x12, 0x32, 0x0a, 0x14, 0x61, 0x75, 0x74, 0x6f, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x65, 0x46, 0x69, 0x72, 0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x14, 0x61, 0x75, 0x74, 0x6f, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x46, 0x69, 0x72,
	0x73, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x54, 0x65, 0x61,
	0x6d, 0x73, 0x50, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0f, 0x6d, 0x61, 0x78, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x50, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x22, 0x82, 0x01, 0x0a, 0x18, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x2a, 0x0a,
	0x10, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x46, 0x6c, 0x6f,
	0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x43, 0x4c, 0x49, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x43, 0x4c, 0x49, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x41, 0x50, 0x49, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x41, 0x50, 0x49, 0x32, 0xa9, 0x01, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x2b, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x1a, 0x0e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x68, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x23, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x1b, 0x5a, 0x19, 0x6b, 0x6c, 0x6f, 0x75, 0x64, 0x6c, 0x69, 0x74, 0x65, 0x2e, 0x69,
	0x6f, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accounts_internal_proto_rawDescOnce sync.Once
	file_accounts_internal_proto_rawDescData = file_accounts_internal_proto_rawDesc
)

func file_accounts_internal_proto_rawDescGZIP() []byte {
	file_accounts_internal_proto_rawDescOnce.Do(func() {
		file_accounts_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_accounts_internal_proto_rawDescData)
	})
	return file_accounts_internal_proto_rawDescData
}

var file_accounts_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_accounts_internal_proto_goTypes = []interface{}{
	(*GetAccountIn)(nil),                        // 0: GetAccountIn
	(*GetAccountOut)(nil),                       // 1: GetAccountOut
	(*GetPlatformSettingsInternalRequest)(nil),  // 2: GetPlatformSettingsInternalRequest
	(*GetPlatformSettingsInternalResponse)(nil), // 3: GetPlatformSettingsInternalResponse
	(*PlatformSettingsInternal)(nil),            // 4: PlatformSettingsInternal
	(*OAuthProviderSettingsInternal)(nil),       // 5: OAuthProviderSettingsInternal
	(*OAuthProviderInternal)(nil),               // 6: OAuthProviderInternal
	(*MicrosoftOAuthProviderInternal)(nil),      // 7: MicrosoftOAuthProviderInternal
	(*TeamSettingsInternal)(nil),                // 8: TeamSettingsInternal
	(*PlatformFeaturesInternal)(nil),            // 9: PlatformFeaturesInternal
}
var file_accounts_internal_proto_depIdxs = []int32{
	4, // 0: GetPlatformSettingsInternalResponse.settings:type_name -> PlatformSettingsInternal
	5, // 1: PlatformSettingsInternal.oauthProviders:type_name -> OAuthProviderSettingsInternal
	8, // 2: PlatformSettingsInternal.teamSettings:type_name -> TeamSettingsInternal
	9, // 3: PlatformSettingsInternal.features:type_name -> PlatformFeaturesInternal
	6, // 4: OAuthProviderSettingsInternal.google:type_name -> OAuthProviderInternal
	6, // 5: OAuthProviderSettingsInternal.github:type_name -> OAuthProviderInternal
	7, // 6: OAuthProviderSettingsInternal.microsoft:type_name -> MicrosoftOAuthProviderInternal
	0, // 7: AccountsInternal.GetAccount:input_type -> GetAccountIn
	2, // 8: AccountsInternal.GetPlatformSettingsInternal:input_type -> GetPlatformSettingsInternalRequest
	1, // 9: AccountsInternal.GetAccount:output_type -> GetAccountOut
	3, // 10: AccountsInternal.GetPlatformSettingsInternal:output_type -> GetPlatformSettingsInternalResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_accounts_internal_proto_init() }
func file_accounts_internal_proto_init() {
	if File_accounts_internal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accounts_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounts_internal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounts_internal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlatformSettingsInternalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounts_internal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlatformSettingsInternalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounts_internal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatformSettingsInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounts_internal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OAuthProviderSettingsInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounts_internal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OAuthProviderInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounts_internal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MicrosoftOAuthProviderInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounts_internal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeamSettingsInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accounts_internal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatformFeaturesInternal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accounts_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounts_internal_proto_goTypes,
		DependencyIndexes: file_accounts_internal_proto_depIdxs,
		MessageInfos:      file_accounts_internal_proto_msgTypes,
	}.Build()
	File_accounts_internal_proto = out.File
	file_accounts_internal_proto_rawDesc = nil
	file_accounts_internal_proto_goTypes = nil
	file_accounts_internal_proto_depIdxs = nil
}
