console:
  replicas: 2
  ingress:
    host: console.kloudlite.io
  env:
    NODE_ENV: production
    PORT: "3000"
    OCI_INSTALLER_JOB_NAME: oci-installer
  secretRef: console-secrets

website:
  replicas: 2
  ingress:
    host: kloudlite.io
  env:
    NODE_ENV: production
    PORT: "3000"
  secretRef: website-secrets
