---
apiVersion: platform.kloudlite.io/v1alpha1
kind: User
metadata:
  name: super-admin
spec:
  email: super-admin@kloudlite.io
  displayName: Super Admin
  roles:
    - super-admin
  active: true
  passwordString: DevPass123!
---
apiVersion: platform.kloudlite.io/v1alpha1
kind: User
metadata:
  name: admin
spec:
  email: admin@kloudlite.io
  displayName: Admin User
  roles:
    - admin
  active: true
  passwordString: DevPass123!
---
apiVersion: platform.kloudlite.io/v1alpha1
kind: User
metadata:
  name: user
spec:
  email: user@kloudlite.io
  displayName: Regular User
  roles:
    - user
  active: true
  passwordString: DevPass123!
