---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workmachine-node-manager
  namespace: wm-user
  labels:
    app: workmachine-node-manager
    kloudlite.io/package-mgmt: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workmachine-node-manager-role
  labels:
    app: workmachine-node-manager
    kloudlite.io/package-mgmt: "true"
rules:
  # PackageRequest permissions
  - apiGroups:
      - packages.kloudlite.io
    resources:
      - packagerequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - packages.kloudlite.io
    resources:
      - packagerequests/status
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workmachine-node-manager-rolebinding
  labels:
    app: workmachine-node-manager
    kloudlite.io/package-mgmt: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workmachine-node-manager-role
subjects:
  - kind: ServiceAccount
    name: workmachine-node-manager
    namespace: wm-user
