import { UserDashboardStats, AdminDashboardStats, UserContext } from '@/types/dashboard';

// Simple user dashboard - only what the user needs to see
export const mockUserDashboardStats: UserDashboardStats = {
  myWorkspaces: {
    online: 3,
    offline: 2,
  },
  myEnvironments: {
    online: 5,
    offline: 1,
  },
  totalEnvironments: {
    online: 42,
    offline: 14,
  },
};

// Comprehensive admin dashboard - full team view
export const mockAdminDashboardStats: AdminDashboardStats = {
  workspaces: {
    total: 34,
    running: 12,
    stopped: 18,
    archived: 4,
  },
  developers: {
    total: 127,
    active: 89,
    admins: 8,
    online: 23,
  },
  nodePools: {
    total: 5,
    healthy: 4,
    degraded: 1,
    failed: 0,
  },
  workMachines: {
    total: 8,
    on: 6,
    off: 2,
    totalCpuCores: 192,
    totalMemoryGB: 768,
    usedCpuCores: 89,
    usedMemoryGB: 312,
    runningEnvironments: 42,
    runningWorkspaces: 12,
    cpuUtilization: 46.4,
    memoryUtilization: 40.6,
  },
  totalResources: {
    totalCpuCores: 480,
    totalMemoryGB: 1920,
    usedCpuCores: 312,
    usedMemoryGB: 856,
    cpuUtilization: 65.0,
    memoryUtilization: 44.6,
  },
  individualWorkMachines: [
    {
      id: 'wm-01',
      developerName: 'Alex Chen',
      status: 'on',
      vmSize: 'm5.2xlarge',
      cpuCores: 8,
      memoryGB: 32,
      storageGB: 100,
      usedCpuCores: 6,
      usedMemoryGB: 24,
      cpuUtilization: 75.0,
      memoryUtilization: 75.0,
      runningWorkspaces: 2,
      runningEnvironments: 3,
      activeWorkloads: 5,
    },
    {
      id: 'wm-02',
      developerName: 'Sarah Kim',
      status: 'on',
      vmSize: 'm5.xlarge',
      cpuCores: 4,
      memoryGB: 16,
      storageGB: 80,
      usedCpuCores: 1,
      usedMemoryGB: 5,
      cpuUtilization: 25.0,
      memoryUtilization: 31.3,
      runningWorkspaces: 1,
      runningEnvironments: 2,
      activeWorkloads: 3,
    },
    {
      id: 'wm-03',
      developerName: 'Mike Johnson',
      status: 'on',
      vmSize: 'm5.4xlarge',
      cpuCores: 16,
      memoryGB: 64,
      storageGB: 200,
      usedCpuCores: 12,
      usedMemoryGB: 48,
      cpuUtilization: 75.0,
      memoryUtilization: 75.0,
      runningWorkspaces: 3,
      runningEnvironments: 4,
      activeWorkloads: 7,
    },
    {
      id: 'wm-04',
      developerName: 'Emma Davis',
      status: 'off',
      vmSize: 'm5.large',
      cpuCores: 2,
      memoryGB: 8,
      storageGB: 50,
      usedCpuCores: 0,
      usedMemoryGB: 0,
      cpuUtilization: 0,
      memoryUtilization: 0,
      runningWorkspaces: 0,
      runningEnvironments: 0,
      activeWorkloads: 0,
    },
  ],
  individualNodePools: [
    {
      id: 'np-01',
      name: 'development-pool',
      status: 'healthy',
      nodeCount: 8,
      vmSize: 'm5.2xlarge',
      cpuPerNode: 8,
      memoryPerNodeGB: 32,
      autoscaleEnabled: true,
      minNodes: 4,
      maxNodes: 12,
      nodeSelector: { environment: 'dev', workload: 'web' },
      region: 'us-west-2',
    },
    {
      id: 'np-02',
      name: 'production-pool',
      status: 'healthy',
      nodeCount: 12,
      vmSize: 'm5.4xlarge',
      cpuPerNode: 16,
      memoryPerNodeGB: 64,
      autoscaleEnabled: true,
      minNodes: 8,
      maxNodes: 20,
      nodeSelector: { environment: 'prod', tier: 'critical' },
      region: 'us-east-1',
    },
    {
      id: 'np-03',
      name: 'staging-pool',
      status: 'degraded',
      nodeCount: 4,
      vmSize: 'm5.xlarge',
      cpuPerNode: 4,
      memoryPerNodeGB: 16,
      autoscaleEnabled: false,
      minNodes: 2,
      maxNodes: 6,
      nodeSelector: { environment: 'staging' },
      region: 'us-west-1',
    },
    {
      id: 'np-04',
      name: 'gpu-pool',
      status: 'healthy',
      nodeCount: 2,
      vmSize: 'p3.2xlarge',
      cpuPerNode: 8,
      memoryPerNodeGB: 61,
      autoscaleEnabled: true,
      minNodes: 1,
      maxNodes: 4,
      nodeSelector: { accelerator: 'nvidia-tesla-v100', workload: 'ml' },
      region: 'us-west-2',
    },
    {
      id: 'np-05',
      name: 'spot-pool',
      status: 'healthy',
      nodeCount: 6,
      vmSize: 'm5.large',
      cpuPerNode: 2,
      memoryPerNodeGB: 8,
      autoscaleEnabled: true,
      minNodes: 2,
      maxNodes: 10,
      nodeSelector: { lifecycle: 'spot', cost: 'optimized' },
      region: 'us-east-1',
    },
  ],
};

// Mock user contexts for testing
export const mockRegularUser: UserContext = {
  role: 'user',
  name: 'Alex Kumar',
  email: 'alex@team.com',
};

export const mockAdminUser: UserContext = {
  role: 'admin',
  name: 'Sarah Chen',
  email: 'sarah@team.com',
};

// Helper function to check if user is admin
export function isAdmin(user: UserContext): boolean {
  return user.role === 'admin' || user.role === 'owner';
}