// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: comms.proto

package comms

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerificationEmailInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Email             string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VerificationToken string                 `protobuf:"bytes,3,opt,name=verificationToken,proto3" json:"verificationToken,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerificationEmailInput) Reset() {
	*x = VerificationEmailInput{}
	mi := &file_comms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationEmailInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationEmailInput) ProtoMessage() {}

func (x *VerificationEmailInput) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationEmailInput.ProtoReflect.Descriptor instead.
func (*VerificationEmailInput) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{0}
}

func (x *VerificationEmailInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerificationEmailInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerificationEmailInput) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

type WelcomeEmailInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeEmailInput) Reset() {
	*x = WelcomeEmailInput{}
	mi := &file_comms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeEmailInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeEmailInput) ProtoMessage() {}

func (x *WelcomeEmailInput) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeEmailInput.ProtoReflect.Descriptor instead.
func (*WelcomeEmailInput) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{1}
}

func (x *WelcomeEmailInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *WelcomeEmailInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PasswordResetEmailInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ResetToken    string                 `protobuf:"bytes,3,opt,name=resetToken,proto3" json:"resetToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResetEmailInput) Reset() {
	*x = PasswordResetEmailInput{}
	mi := &file_comms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResetEmailInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResetEmailInput) ProtoMessage() {}

func (x *PasswordResetEmailInput) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResetEmailInput.ProtoReflect.Descriptor instead.
func (*PasswordResetEmailInput) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{2}
}

func (x *PasswordResetEmailInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PasswordResetEmailInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PasswordResetEmailInput) GetResetToken() string {
	if x != nil {
		return x.ResetToken
	}
	return ""
}

type AccountMemberInviteEmailInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountName     string                 `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"`
	InvitationToken string                 `protobuf:"bytes,2,opt,name=invitationToken,proto3" json:"invitationToken,omitempty"`
	InvitedBy       string                 `protobuf:"bytes,3,opt,name=invitedBy,proto3" json:"invitedBy,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountMemberInviteEmailInput) Reset() {
	*x = AccountMemberInviteEmailInput{}
	mi := &file_comms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountMemberInviteEmailInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountMemberInviteEmailInput) ProtoMessage() {}

func (x *AccountMemberInviteEmailInput) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountMemberInviteEmailInput.ProtoReflect.Descriptor instead.
func (*AccountMemberInviteEmailInput) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{3}
}

func (x *AccountMemberInviteEmailInput) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AccountMemberInviteEmailInput) GetInvitationToken() string {
	if x != nil {
		return x.InvitationToken
	}
	return ""
}

func (x *AccountMemberInviteEmailInput) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

func (x *AccountMemberInviteEmailInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AccountMemberInviteEmailInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectMemberInviteEmailInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectName     string                 `protobuf:"bytes,1,opt,name=projectName,proto3" json:"projectName,omitempty"`
	InvitationToken string                 `protobuf:"bytes,2,opt,name=invitationToken,proto3" json:"invitationToken,omitempty"`
	InvitedBy       string                 `protobuf:"bytes,3,opt,name=invitedBy,proto3" json:"invitedBy,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProjectMemberInviteEmailInput) Reset() {
	*x = ProjectMemberInviteEmailInput{}
	mi := &file_comms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberInviteEmailInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberInviteEmailInput) ProtoMessage() {}

func (x *ProjectMemberInviteEmailInput) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberInviteEmailInput.ProtoReflect.Descriptor instead.
func (*ProjectMemberInviteEmailInput) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectMemberInviteEmailInput) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ProjectMemberInviteEmailInput) GetInvitationToken() string {
	if x != nil {
		return x.InvitationToken
	}
	return ""
}

func (x *ProjectMemberInviteEmailInput) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

func (x *ProjectMemberInviteEmailInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProjectMemberInviteEmailInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SendContactUsEmailInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CompanyName   string                 `protobuf:"bytes,3,opt,name=companyName,proto3" json:"companyName,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	MobileNumber  string                 `protobuf:"bytes,5,opt,name=mobileNumber,proto3" json:"mobileNumber,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendContactUsEmailInput) Reset() {
	*x = SendContactUsEmailInput{}
	mi := &file_comms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendContactUsEmailInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendContactUsEmailInput) ProtoMessage() {}

func (x *SendContactUsEmailInput) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendContactUsEmailInput.ProtoReflect.Descriptor instead.
func (*SendContactUsEmailInput) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{5}
}

func (x *SendContactUsEmailInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendContactUsEmailInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SendContactUsEmailInput) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *SendContactUsEmailInput) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *SendContactUsEmailInput) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *SendContactUsEmailInput) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_comms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{6}
}

var File_comms_proto protoreflect.FileDescriptor

const file_comms_proto_rawDesc = "" +
	"\n" +
	"\vcomms.proto\"p\n" +
	"\x16VerificationEmailInput\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x11verificationToken\x18\x03 \x01(\tR\x11verificationToken\"=\n" +
	"\x11WelcomeEmailInput\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"c\n" +
	"\x17PasswordResetEmailInput\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"resetToken\x18\x03 \x01(\tR\n" +
	"resetToken\"\xb3\x01\n" +
	"\x1dAccountMemberInviteEmailInput\x12 \n" +
	"\vaccountName\x18\x01 \x01(\tR\vaccountName\x12(\n" +
	"\x0finvitationToken\x18\x02 \x01(\tR\x0finvitationToken\x12\x1c\n" +
	"\tinvitedBy\x18\x03 \x01(\tR\tinvitedBy\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\xb3\x01\n" +
	"\x1dProjectMemberInviteEmailInput\x12 \n" +
	"\vprojectName\x18\x01 \x01(\tR\vprojectName\x12(\n" +
	"\x0finvitationToken\x18\x02 \x01(\tR\x0finvitationToken\x12\x1c\n" +
	"\tinvitedBy\x18\x03 \x01(\tR\tinvitedBy\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\xbd\x01\n" +
	"\x17SendContactUsEmailInput\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vcompanyName\x18\x03 \x01(\tR\vcompanyName\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\"\n" +
	"\fmobileNumber\x18\x05 \x01(\tR\fmobileNumber\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\x06\n" +
	"\x04Void2\x9e\x03\n" +
	"\x05Comms\x127\n" +
	"\x15SendVerificationEmail\x12\x17.VerificationEmailInput\x1a\x05.Void\x129\n" +
	"\x16SendPasswordResetEmail\x12\x18.PasswordResetEmailInput\x1a\x05.Void\x12E\n" +
	"\x1cSendAccountMemberInviteEmail\x12\x1e.AccountMemberInviteEmailInput\x1a\x05.Void\x12E\n" +
	"\x1cSendProjectMemberInviteEmail\x12\x1e.ProjectMemberInviteEmailInput\x1a\x05.Void\x12-\n" +
	"\x10SendWelcomeEmail\x12\x12.WelcomeEmailInput\x1a\x05.Void\x12-\n" +
	"\x10SendWaitingEmail\x12\x12.WelcomeEmailInput\x1a\x05.Void\x125\n" +
	"\x12SendContactUsEmail\x12\x18.SendContactUsEmailInput\x1a\x05.VoidB\x18Z\x16kloudlite.io/rpc/commsb\x06proto3"

var (
	file_comms_proto_rawDescOnce sync.Once
	file_comms_proto_rawDescData []byte
)

func file_comms_proto_rawDescGZIP() []byte {
	file_comms_proto_rawDescOnce.Do(func() {
		file_comms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comms_proto_rawDesc), len(file_comms_proto_rawDesc)))
	})
	return file_comms_proto_rawDescData
}

var file_comms_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_comms_proto_goTypes = []any{
	(*VerificationEmailInput)(nil),        // 0: VerificationEmailInput
	(*WelcomeEmailInput)(nil),             // 1: WelcomeEmailInput
	(*PasswordResetEmailInput)(nil),       // 2: PasswordResetEmailInput
	(*AccountMemberInviteEmailInput)(nil), // 3: AccountMemberInviteEmailInput
	(*ProjectMemberInviteEmailInput)(nil), // 4: ProjectMemberInviteEmailInput
	(*SendContactUsEmailInput)(nil),       // 5: SendContactUsEmailInput
	(*Void)(nil),                          // 6: Void
}
var file_comms_proto_depIdxs = []int32{
	0, // 0: Comms.SendVerificationEmail:input_type -> VerificationEmailInput
	2, // 1: Comms.SendPasswordResetEmail:input_type -> PasswordResetEmailInput
	3, // 2: Comms.SendAccountMemberInviteEmail:input_type -> AccountMemberInviteEmailInput
	4, // 3: Comms.SendProjectMemberInviteEmail:input_type -> ProjectMemberInviteEmailInput
	1, // 4: Comms.SendWelcomeEmail:input_type -> WelcomeEmailInput
	1, // 5: Comms.SendWaitingEmail:input_type -> WelcomeEmailInput
	5, // 6: Comms.SendContactUsEmail:input_type -> SendContactUsEmailInput
	6, // 7: Comms.SendVerificationEmail:output_type -> Void
	6, // 8: Comms.SendPasswordResetEmail:output_type -> Void
	6, // 9: Comms.SendAccountMemberInviteEmail:output_type -> Void
	6, // 10: Comms.SendProjectMemberInviteEmail:output_type -> Void
	6, // 11: Comms.SendWelcomeEmail:output_type -> Void
	6, // 12: Comms.SendWaitingEmail:output_type -> Void
	6, // 13: Comms.SendContactUsEmail:output_type -> Void
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comms_proto_init() }
func file_comms_proto_init() {
	if File_comms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comms_proto_rawDesc), len(file_comms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comms_proto_goTypes,
		DependencyIndexes: file_comms_proto_depIdxs,
		MessageInfos:      file_comms_proto_msgTypes,
	}.Build()
	File_comms_proto = out.File
	file_comms_proto_goTypes = nil
	file_comms_proto_depIdxs = nil
}
