// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: jseval.proto

package jseval

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvalIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Init          string                 `protobuf:"bytes,1,opt,name=init,proto3" json:"init,omitempty"`
	FunName       string                 `protobuf:"bytes,4,opt,name=funName,proto3" json:"funName,omitempty"`
	Inputs        *anypb.Any             `protobuf:"bytes,3,opt,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalIn) Reset() {
	*x = EvalIn{}
	mi := &file_jseval_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalIn) ProtoMessage() {}

func (x *EvalIn) ProtoReflect() protoreflect.Message {
	mi := &file_jseval_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalIn.ProtoReflect.Descriptor instead.
func (*EvalIn) Descriptor() ([]byte, []int) {
	return file_jseval_proto_rawDescGZIP(), []int{0}
}

func (x *EvalIn) GetInit() string {
	if x != nil {
		return x.Init
	}
	return ""
}

func (x *EvalIn) GetFunName() string {
	if x != nil {
		return x.FunName
	}
	return ""
}

func (x *EvalIn) GetInputs() *anypb.Any {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type EvalOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *anypb.Any             `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalOut) Reset() {
	*x = EvalOut{}
	mi := &file_jseval_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalOut) ProtoMessage() {}

func (x *EvalOut) ProtoReflect() protoreflect.Message {
	mi := &file_jseval_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalOut.ProtoReflect.Descriptor instead.
func (*EvalOut) Descriptor() ([]byte, []int) {
	return file_jseval_proto_rawDescGZIP(), []int{1}
}

func (x *EvalOut) GetOutput() *anypb.Any {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_jseval_proto protoreflect.FileDescriptor

const file_jseval_proto_rawDesc = "" +
	"\n" +
	"\fjseval.proto\x1a\x19google/protobuf/any.proto\"d\n" +
	"\x06EvalIn\x12\x12\n" +
	"\x04init\x18\x01 \x01(\tR\x04init\x12\x18\n" +
	"\afunName\x18\x04 \x01(\tR\afunName\x12,\n" +
	"\x06inputs\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x06inputs\"7\n" +
	"\aEvalOut\x12,\n" +
	"\x06output\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x06output2#\n" +
	"\x06JSEval\x12\x19\n" +
	"\x04Eval\x12\a.EvalIn\x1a\b.EvalOutB\x19Z\x17kloudlite.io/rpc/jsevalb\x06proto3"

var (
	file_jseval_proto_rawDescOnce sync.Once
	file_jseval_proto_rawDescData []byte
)

func file_jseval_proto_rawDescGZIP() []byte {
	file_jseval_proto_rawDescOnce.Do(func() {
		file_jseval_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jseval_proto_rawDesc), len(file_jseval_proto_rawDesc)))
	})
	return file_jseval_proto_rawDescData
}

var file_jseval_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jseval_proto_goTypes = []any{
	(*EvalIn)(nil),    // 0: EvalIn
	(*EvalOut)(nil),   // 1: EvalOut
	(*anypb.Any)(nil), // 2: google.protobuf.Any
}
var file_jseval_proto_depIdxs = []int32{
	2, // 0: EvalIn.inputs:type_name -> google.protobuf.Any
	2, // 1: EvalOut.output:type_name -> google.protobuf.Any
	0, // 2: JSEval.Eval:input_type -> EvalIn
	1, // 3: JSEval.Eval:output_type -> EvalOut
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_jseval_proto_init() }
func file_jseval_proto_init() {
	if File_jseval_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jseval_proto_rawDesc), len(file_jseval_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jseval_proto_goTypes,
		DependencyIndexes: file_jseval_proto_depIdxs,
		MessageInfos:      file_jseval_proto_msgTypes,
	}.Build()
	File_jseval_proto = out.File
	file_jseval_proto_goTypes = nil
	file_jseval_proto_depIdxs = nil
}
