dev: export KAFKA_BOOTSTRAP_SERVERS=kafka-kafka-0.kafka-kafka-brokers.hotspot:9092,kafka-kafka-1.kafka-kafka-brokers.hotspot:9092
dev: export KAFKA_TOPICS=dev-hotspot-infra
dev: export KAFKA_GROUP_ID=dev-hotspot-infra
dev:
	go run ./main.go
