# syntax=docker/dockerfile:1.4
FROM gcr.io/distroless/static:nonroot

ARG USER="65532"
ARG USER_GROUP="65532"

WORKDIR /app
ARG binary
COPY --chown=${USER}:${USER_GROUP} --from=builder ${binary} ./kloudlite-agent
USER ${USER}:${USER_GROUP}
ENTRYPOINT ["./kloudlite-agent"]
