FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /app
# COPY --from=docker.io/redpandadata/redapanda:latest /opt/redpanda/bin/rpk /usr/local/bin/rpk
COPY --from=docker.redpanda.com/redpandadata/redpanda:latest /opt/redpanda/bin/rpk /usr/local/bin/rpk
ARG binpath
COPY --from=local-builder ${binpath} ./messages-distribution-worker
ENTRYPOINT [ "./messages-distribution-worker" ]
