# vim:set ft=dockerfile:
# FROM gcr.io/distroless/static:nonroot

# because redpanda operator is using rpk binary, we need to have bash, rpk and grep in our binary too

FROM alpine:3.16
RUN apk add bash

COPY --from=docker.io/vectorized/redpanda:v22.1.6 /usr/bin/rpk /usr/local/bin/rpk
COPY --from=docker.io/vectorized/redpanda:v22.1.6 /opt/redpanda/libexec/rpk /opt/redpanda/libexec/rpk

ARG binpath
COPY --from=local-builder ${binpath} /manager

USER 65532:65532
ENTRYPOINT ["/manager"]
