FROM gcr.io/distroless/static:nonroot
COPY --from=docker.io/bitnami/kubectl /opt/bitnami/kubectl/bin/kubectl /usr/local/bin/kubectl
ARG BINARY
COPY ./bin/${BINARY} /manager
USER 65532:65532
ENTRYPOINT [ "/manager" ]
