apiVersion: environments.kloudlite.io/v1
kind: HelmChart
metadata:
  name: nginx-test
  namespace: default
spec:
  chart:
    url: https://charts.bitnami.com/bitnami
    name: nginx
    version: "18.2.4"
  helmValues:
    replicaCount: 2
  jobVars:
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1000m"
        memory: "1000Mi"
