version: 3

tasks:
  build:kloudlite:
    env:
      CGO_ENABLED: 0
    cmds:
      - go build -ldflags='-s -w' -o bin/kloudlite ./cli/kloudlite/

  build:server:
    cmds:
      - task: build:kloudlite

  build:tunnel-server:
    cmds:
      - task: build:kloudlite

  build:oci-installer:
    env:
      CGO_ENABLED: 0
    cmds:
      - go build -ldflags='-s -w' -o bin/oci-installer ./cli/kli/oci-installer/

  manifests:
    cmds:
      # generate CRDs from type definitions
      - controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=manifests

      # generate deep copy go files
      - controller-gen object paths="./..."
      # - controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:stdout

  consolidate-crds:
    desc: Consolidate all CRD manifests into single file for kli
    cmds:
      - cat manifests/*.yaml > cli/kli/internal/manifests/crds.yaml
      - echo "Consolidated CRDs into cli/kli/internal/manifests/crds.yaml"
