import * as Chips from '~/components/atoms/chips';

export const dummyData = {
  appliedFilters: [
    {
      id: '0',
      label: 'Active',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Status:',
    },
    {
      id: '1',
      label: 'Plaxonic',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Cluster:',
    },
    {
      id: '3',
      label: 'Plaxonic1',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Cluster:',
    },
    {
      id: '4',
      label: 'Plaxonic2',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Cluster',
    },
    {
      id: '5',
      label: 'Plaxonic3',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Cluster:',
    },
    {
      id: '6',
      label: 'Plaxonic4',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Cluster:',
    },
  ],
  cloudProvidersList: [
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app1',
      providerRegion: 'Amazon Web Services',
      author: 'Reyan updated the project',
      status: 'Verified',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app2',
      providerRegion: 'Amazon Web Services',
      author: 'Reyan updated the project',
      status: 'Verified',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app3',
      providerRegion: 'Amazon Web Services',
      author: 'Reyan updated the project',
      status: 'Verified',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app4',
      providerRegion: 'Amazon Web Services',
      author: 'Reyan updated the project',
      status: 'Verified',
      lastupdated: '3 days ago',
    },
  ],
  projectList: [
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app1',
      cluster: 'Plaxonic',
      path: 'dusty-crossbow.com/projects',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app2',
      cluster: 'Plaxonic',
      path: 'dusty-crossbow.com/projects',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app3',
      cluster: 'Plaxonic',
      path: 'dusty-crossbow.com/projects',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app4',
      cluster: 'Plaxonic',
      path: 'dusty-crossbow.com/projects',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
  ],
  clusterList: [
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app1',
      providerRegion: 'AWS, India',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app2',
      providerRegion: 'AWS, India',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app3',
      providerRegion: 'AWS, India',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app4',
      providerRegion: 'AWS, India',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
  ],
  containerRegistryGeneralList: [
    {
      name: 'Succinct',
      id: 'succinctrepo.com/samplegame.com:latest',
      builds: 18,
      tags: ['Linux', 'IBM Z', 'Riscv 64', 'ARM 64', 'ARM', 'PowerPC'],
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Succinct',
      id: 'succinctrepo.com/samplegame.com:latest1',
      builds: 18,
      tags: ['Linux', 'IBM Z', 'Riscv 64', 'ARM 64', 'ARM', 'PowerPC'],
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Succinct',
      id: 'succinctrepo.com/samplegame.com:latest2',
      builds: 18,
      tags: ['Linux', 'IBM Z', 'Riscv 64', 'ARM 64', 'ARM', 'PowerPC'],
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Succinct',
      id: 'succinctrepo.com/samplegame.com:latest3',
      builds: 18,
      tags: ['Linux', 'IBM Z', 'Riscv 64', 'ARM 64', 'ARM', 'PowerPC'],
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Succinct',
      id: 'succinctrepo.com/samplegame.com:latest4',
      builds: 18,
      tags: ['Linux', 'IBM Z', 'Riscv 64', 'ARM 64', 'ARM', 'PowerPC'],
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
  ],
  containerRegistryAccessManagementList: [
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest1',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest2',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest3',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest4',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest5',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
  ],
  projectConfig: [
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest1',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest2',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest3',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest4',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest5',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
  ],
  providers: [
    { checked: false, content: 'AWS', id: 'aws' },
    { checked: false, content: 'Azure', id: 'azure' },
    { checked: false, content: 'CloudStack', id: 'cloudstack' },
    { checked: false, content: 'Digital Ocean', id: 'digitalocean' },
  ],
};
