import * as Chips from '~/components/atoms/chips';

export const dummyData = {
  appliedFilters: [
    {
      id: '0',
      label: 'Active',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Status:',
    },
    {
      id: '1',
      label: 'Plaxonic',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Cluster:',
    },
    {
      id: '3',
      label: 'Plaxonic1',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Cluster:',
    },
    {
      id: '4',
      label: 'Plaxonic2',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Cluster',
    },
    {
      id: '5',
      label: 'Plaxonic3',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Cluster:',
    },
    {
      id: '6',
      label: 'Plaxonic4',
      type: Chips.ChipType.REMOVABLE,
      prefix: 'Cluster:',
    },
  ],
  cloudProvidersList: [
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app1',
      providerRegion: 'Amazon Web Services',
      author: 'Reyan updated the project',
      status: 'Verified',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app2',
      providerRegion: 'Amazon Web Services',
      author: 'Reyan updated the project',
      status: 'Verified',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app3',
      providerRegion: 'Amazon Web Services',
      author: 'Reyan updated the project',
      status: 'Verified',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app4',
      providerRegion: 'Amazon Web Services',
      author: 'Reyan updated the project',
      status: 'Verified',
      lastupdated: '3 days ago',
    },
  ],
  projectList: [
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app1',
      cluster: 'Plaxonic',
      path: 'dusty-crossbow.com/projects',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app2',
      cluster: 'Plaxonic',
      path: 'dusty-crossbow.com/projects',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app3',
      cluster: 'Plaxonic',
      path: 'dusty-crossbow.com/projects',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app4',
      cluster: 'Plaxonic',
      path: 'dusty-crossbow.com/projects',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
  ],
  clusterList: [
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app1',
      providerRegion: 'AWS, India',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app2',
      providerRegion: 'AWS, India',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app3',
      providerRegion: 'AWS, India',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
    {
      name: 'Lobster early',
      id: 'lobster-early-kloudlite-app4',
      providerRegion: 'AWS, India',
      author: 'Reyan updated the project',
      lastupdated: '3 days ago',
    },
  ],
  containerRegistryGeneralList: [
    {
      name: 'Succinct',
      id: 'succinctrepo.com/samplegame.com:latest',
      builds: 18,
      tags: ['Linux', 'IBM Z', 'Riscv 64', 'ARM 64', 'ARM', 'PowerPC'],
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Succinct',
      id: 'succinctrepo.com/samplegame.com:latest1',
      builds: 18,
      tags: ['Linux', 'IBM Z', 'Riscv 64', 'ARM 64', 'ARM', 'PowerPC'],
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Succinct',
      id: 'succinctrepo.com/samplegame.com:latest2',
      builds: 18,
      tags: ['Linux', 'IBM Z', 'Riscv 64', 'ARM 64', 'ARM', 'PowerPC'],
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Succinct',
      id: 'succinctrepo.com/samplegame.com:latest3',
      builds: 18,
      tags: ['Linux', 'IBM Z', 'Riscv 64', 'ARM 64', 'ARM', 'PowerPC'],
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Succinct',
      id: 'succinctrepo.com/samplegame.com:latest4',
      builds: 18,
      tags: ['Linux', 'IBM Z', 'Riscv 64', 'ARM 64', 'ARM', 'PowerPC'],
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
  ],
  containerRegistryAccessManagementList: [
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest1',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest2',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest3',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest4',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
    {
      name: 'Maynard_Channel_Access',
      id: 'succinctrepo.com/samplegame.com:latest5',
      permissions: 'Read & Write',
      author: 'Reyan updated the link',
      lastupdated: '3 days ago',
    },
  ],
  projectConfig: [
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest1',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest2',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest3',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest4',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
    {
      name: 'kloud-root-ca.crt',
      id: 'succinctrepo.com/samplegame.com:latest5',
      entries: '18 entries',
      lastupdated: 'Last updated by Reyan, May 12, 2023 9:59 PM GMT+5:30',
    },
  ],
  devices: [
    {
      name: 'dot-matrix-ms-brandlerich',
      id: 'fsdUneUsWLCUqePc4gvmnJNCurlxRNvwnOU1',
      ip: '192.168.64.1 - c2s.provisioning.test.vpc',
      author: 'Susan Smith',
      cluster: 'Plaxonic',
      activity: 'Reyan updated the link',
      lastupdated: '3 days ago',
      category: 'personal',
    },
    {
      name: 'dot-matrix-ms-brandlerich',
      id: 'fsdUneUsWLCUqePc4gvmnJNCurlxRNvwnOU2',
      ip: '192.168.64.2 - c2s.provisioning.test.vpc',
      author: 'Susan Smith',
      cluster: 'Plaxonic',
      activity: 'Reyan updated the link',
      lastupdated: '3 days ago',
      category: 'personal',
    },
    {
      name: 'dot-matrix-ms-brandlerich',
      id: 'fsdUneUsWLCUqePc4gvmnJNCurlxRNvwnOU3',
      ip: '192.168.64.3 - c2s.provisioning.test.vpc',
      author: 'Susan Smith',
      cluster: 'Plaxonic',
      activity: 'Reyan updated the link',
      lastupdated: '3 days ago',
      category: 'team',
    },
    {
      name: 'dot-matrix-ms-brandlerich',
      id: 'fsdUneUsWLCUqePc4gvmnJNCurlxRNvwnOU4',
      ip: '192.168.64.4 - c2s.provisioning.test.vpc',
      author: 'Susan Smith',
      cluster: 'Plaxonic',
      activity: 'Reyan updated the link',
      lastupdated: '3 days ago',
      category: 'team',
    },
    {
      name: 'dot-matrix-ms-brandlerich',
      id: 'fsdUneUsWLCUqePc4gvmnJNCurlxRNvwnOU5',
      ip: '192.168.64.5 - c2s.provisioning.test.vpc',
      author: 'Susan Smith',
      cluster: 'Plaxonic',
      activity: 'Reyan updated the link',
      lastupdated: '3 days ago',
      category: 'team',
    },
    {
      name: 'dot-matrix-ms-brandlerich',
      id: 'fsdUneUsWLCUqePc4gvmnJNCurlxRNvwnOU6',
      ip: '192.168.64.6 - c2s.provisioning.test.vpc',
      author: 'Susan Smith',
      cluster: 'Plaxonic',
      activity: 'Reyan updated the link',
      lastupdated: '3 days ago',
      category: 'team',
    },
  ],
  cluster: [
    {
      name: 'Agenpool',
      id: 'succinctrepo.com/samplegame.com:latest',
      status: 'Running',
      capacity: '3 min - 30 max',
      nodeplan: 'CPU Optimised-1x',
      provisionType: 'On-demand',
      createdAt: '5/18/23, 3:30 PM',
      nodes: [
        { id: 1, status: 'running', ip: '12.172.24.47', name: 'Node 1' },
        { id: 2, status: 'running', ip: '12.172.24.47', name: 'Node 2' },
        { id: 3, status: 'running', ip: '12.172.24.47', name: 'Node 3' },
        { id: 4, status: 'running', ip: '12.172.24.47', name: 'Node 4' },
        { id: 5, status: 'starting', ip: '12.172.24.47', name: 'Node 5' },
        { id: 6, status: 'starting', ip: '12.172.24.47', name: 'Node 6' },
        { id: 7, status: 'stopped', ip: '12.172.24.47', name: 'Node 7' },
        { id: 8, status: 'stopped', ip: '12.172.24.47', name: 'Node 8' },
      ],
    },
    {
      name: 'Agenpool',
      id: 'succinctrepo.com/samplegame.com:latest1',
      status: 'Running',
      capacity: '3 min - 30 max',
      nodeplan: 'CPU Optimised-1x',
      provisionType: 'On-demand',
      createdAt: '5/18/23, 3:30 PM',
      nodes: [
        { id: 1, status: 'running', ip: '12.172.24.47', name: 'Node 1' },
        { id: 2, status: 'running', ip: '12.172.24.47', name: 'Node 2' },
        { id: 3, status: 'running', ip: '12.172.24.47', name: 'Node 3' },
        { id: 4, status: 'running', ip: '12.172.24.47', name: 'Node 4' },
        { id: 5, status: 'starting', ip: '12.172.24.47', name: 'Node 5' },
        { id: 6, status: 'starting', ip: '12.172.24.47', name: 'Node 6' },
        { id: 7, status: 'stopped', ip: '12.172.24.47', name: 'Node 7' },
        { id: 8, status: 'stopped', ip: '12.172.24.47', name: 'Node 8' },
      ],
    },
    {
      name: 'Agenpool',
      id: 'succinctrepo.com/samplegame.com:latest2',
      status: 'Running',
      capacity: '3 min - 30 max',
      nodeplan: 'CPU Optimised-1x',
      provisionType: 'On-demand',
      createdAt: '5/18/23, 3:30 PM',
      nodes: [
        { id: 1, status: 'running', ip: '12.172.24.47', name: 'Node 1' },
        { id: 2, status: 'running', ip: '12.172.24.47', name: 'Node 2' },
        { id: 3, status: 'starting', ip: '12.172.24.47', name: 'Node 3' },
        { id: 4, status: 'stopped', ip: '12.172.24.47', name: 'Node 4' },
        { id: 5, status: 'starting', ip: '12.172.24.47', name: 'Node 5' },
        { id: 6, status: 'starting', ip: '12.172.24.47', name: 'Node 6' },
        { id: 7, status: 'stopped', ip: '12.172.24.47', name: 'Node 7' },
        { id: 8, status: 'stopped', ip: '12.172.24.47', name: 'Node 8' },
      ],
    },
    {
      name: 'Agenpool',
      id: 'succinctrepo.com/samplegame.com:latest3',
      status: 'Running',
      capacity: '3 min - 30 max',
      nodeplan: 'CPU Optimised-1x',
      provisionType: 'On-demand',
      createdAt: '5/18/23, 3:30 PM',
      nodes: [
        { id: 1, status: 'running', ip: '12.172.24.47', name: 'Node 1' },
        { id: 2, status: 'running', ip: '12.172.24.47', name: 'Node 2' },
        { id: 3, status: 'running', ip: '12.172.24.47', name: 'Node 3' },
        { id: 4, status: 'starting', ip: '12.172.24.47', name: 'Node 4' },
        { id: 5, status: 'starting', ip: '12.172.24.47', name: 'Node 5' },
        { id: 6, status: 'stopped', ip: '12.172.24.47', name: 'Node 6' },
        { id: 7, status: 'stopped', ip: '12.172.24.47', name: 'Node 7' },
        { id: 8, status: 'stopped', ip: '12.172.24.47', name: 'Node 8' },
      ],
    },
    {
      name: 'Agenpool',
      id: 'succinctrepo.com/samplegame.com:latest4',
      status: 'Running',
      capacity: '3 min - 30 max',
      nodeplan: 'CPU Optimised-1x',
      provisionType: 'On-demand',
      createdAt: '5/18/23, 3:30 PM',
      nodes: [
        { id: 1, status: 'running', ip: '12.172.24.47', name: 'Node 1' },
        { id: 2, status: 'running', ip: '12.172.24.47', name: 'Node 2' },
        { id: 3, status: 'running', ip: '12.172.24.47', name: 'Node 3' },
        { id: 4, status: 'starting', ip: '12.172.24.47', name: 'Node 4' },
        { id: 5, status: 'starting', ip: '12.172.24.47', name: 'Node 5' },
        { id: 6, status: 'starting', ip: '12.172.24.47', name: 'Node 6' },
        { id: 7, status: 'stopped', ip: '12.172.24.47', name: 'Node 7' },
        { id: 8, status: 'stopped', ip: '12.172.24.47', name: 'Node 8' },
      ],
    },
  ],
  nodePlans: [
    {
      id: 'np1',
      label: 'CPU Optimised',
      value: 'CPU Optimised',
      disabled: true,
    },
    {
      id: 'np2',
      label: '1x - small - 2VCPU 3.75GB Memory',
      value: '1x - small - 2VCPU 3.75GB Memory',
      disabled: false,
    },
    {
      id: 'np3',
      label: '2x - medium - 2VCPU 3.75GB Memory',
      value: '2x - medium - 2VCPU 3.75GB Memory',
      disabled: false,
    },
    {
      id: 'np4',
      label: '3x - large - 2VCPU 3.75GB Memory',
      value: '3x - large - 2VCPU 3.75GB Memory',
      disabled: false,
    },
    {
      id: 'np5',
      label: '4x - extra-large - 2VCPU 3.75GB Memory',
      value: '4x - extra-large - 2VCPU 3.75GB Memory',
      disabled: false,
    },
    {
      id: 'np6',
      label: 'Memory Optimised',
      value: 'Memory Optimised',
      disabled: true,
    },
    {
      id: 'np7',
      label: '1x - small - 2vCPU 8GB Memory',
      value: '1x - small - 2vCPU 8GB Memory',
      disabled: false,
    },
    {
      id: 'np8',
      label: '2x - medium - 2vCPU 8GB Memory',
      value: '2x - medium - 2vCPU 8GB Memory',
      disabled: false,
    },
    {
      id: 'np9',
      label: '3x - large - 2vCPU 8GB Memory',
      value: '3x - large - 2vCPU 8GB Memory',
      disabled: false,
    },
    {
      id: 'np10',
      label: '4x - extra large - 2vCPU 8GB Memory',
      value: '4x - extra large - 2vCPU 8GB Memory',
      disabled: false,
    },
    {
      id: 'np11',
      label: 'General purpose',
      value: 'General purpose',
      disabled: true,
    },
    {
      id: 'np12',
      label: '1x - small - 2vCPU 8GB Memory',
      value: '1x - small - 2vCPU 8GB Memory',
      disabled: false,
    },
    {
      id: 'np13',
      label: '2x - medium - 2vCPU 8GB Memory',
      value: '2x - medium - 2vCPU 8GB Memory',
      disabled: false,
    },
    {
      id: 'np14',
      label: '3x - large - 2vCPU 8GB Memory',
      value: '3x - large - 2vCPU 8GB Memory',
      disabled: false,
    },
    {
      id: 'np15',
      label: '4x - extra large - 2vCPU 8GB Memory',
      value: '4x - extra large - 2vCPU 8GB Memory',
      disabled: false,
    },
  ],
  provisionTypes: [
    { id: 'pt1', label: 'On-Demand', value: 'On-Demand' },
    { id: 'pt2', label: 'Spot 70% discount', value: 'Spot 70% discount' },
    {
      id: 'pt3',
      label: 'Reserved 80% discount',
      value: 'Reserved 80% discount',
    },
  ],
  taints: [
    { id: 't1', label: 'No execute', value: 'No execute' },
    { id: 't2', label: 'No schedule', value: 'No schedule' },
    {
      id: 't3',
      label: 'Preferred no schedule',
      value: 'Preferred no schedule',
    },
  ],
  providers: [
    { checked: false, content: 'AWS', id: 'aws' },
    { checked: false, content: 'Azure', id: 'azure' },
    { checked: false, content: 'CloudStack', id: 'cloudstack' },
    { checked: false, content: 'Digital Ocean', id: 'digitalocean' },
  ],
};
