#!/usr/bin/env sh

case $1 in
  "auth")
    PORT=3000
    ;;

  "console")
    PORT=3001
    ;;

  *)
    PORT=5000
    ;;
esac

APP=$1 PORT=$PORT REMIX_DEV_ORIGIN="https://$1.dev.kloudlite.io" pnpm dev
