FROM node:20.8.1-alpine as node
WORKDIR  /app

COPY ./src/apps/devdoc ./src/apps/devdoc
COPY ./src/design-system/tailwind-base.js ./src/design-system/tailwind-base.js
COPY ./src/design-system/css-plugins ./src/design-system/css-plugins
COPY ./src/design-system/css ./src/design-system/css
COPY ./src/design-system/out ./src/design-system/out

WORKDIR /app/src/apps/devdoc

RUN npm i -g pnpm
RUN pnpm i -p

RUN npm run build

ENTRYPOINT pnpm start