#!/usr/bin/env sh

case $1 in
  "auth")
    PORT=3000
    ;;

  "console")
    PORT=3001
    ;;

  "website")
      PORT=3005
      ;;

  "devdoc")
      PORT=3006
      ;;

  *)
    PORT=5000
    ;;
esac

case $3 in
  "local")
    REMIX_DEV_ORIGIN=http://localhost
    IS_LOCAL="true"
    ;;

  *)
    REMIX_DEV_ORIGIN="https://$1.dev.kloudlite.io"
    IS_LOCAL="false"

    ;;

esac


APP=$1 PORT=$PORT  REMIX_DEV_ORIGIN=$REMIX_DEV_ORIGIN IS_LOCAL=$IS_LOCAL pnpm $2
